// OPTIONAL (§9): pre-seed `licenses` rows from the website's claim records so
// legacy holders auto-claim instantly by email — without this, rows are
// created on their first /claim-legacy call, which also works.
//
// Ed25519 is deterministic (RFC 8032): re-signing the exact payload the
// website signed yields the exact token the customer holds, so we can compute
// legacy_token_hash without ever having stored the raw tokens.
//
//   Input: JSON export of claim records: [{ "email", "plan", "issuedAt" }, ...]
//          (lib/claims.ts ClaimRecord shape; the admin page can produce this)
//   LICENSE_PRIVATE_KEY='<pem or base64-of-pem>' \
//     deno run -A scripts/seed-legacy.ts claims-export.json > seed.sql
//
// IMPORTANT: `email` must be byte-for-byte what the website signed (the raw
// record value, NOT normalized) or the token won't match. The generated SQL
// stores the normalized form in buyer_email, per schema.

const subtle = globalThis.crypto.subtle

function pemToDer(pem: string): Uint8Array {
  const b64 = pem.replace(/-----[^-]+-----/g, '').replace(/\s/g, '')
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0))
}

function b64url(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

async function sha256Hex(input: string): Promise<string> {
  const digest = await subtle.digest('SHA-256', new TextEncoder().encode(input))
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, '0')).join('')
}

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

const rawKey = Deno.env.get('LICENSE_PRIVATE_KEY')
if (!rawKey) throw new Error('LICENSE_PRIVATE_KEY is not set')
const pem = rawKey.includes('BEGIN') ? rawKey : atob(rawKey.replace(/\s/g, ''))
const privateKey = await subtle.importKey('pkcs8', pemToDer(pem).buffer as ArrayBuffer, { name: 'Ed25519' }, false, ['sign'])

const inputPath = Deno.args[0]
if (!inputPath) throw new Error('Usage: deno run -A scripts/seed-legacy.ts <claims-export.json>')
const records = JSON.parse(await Deno.readTextFile(inputPath)) as Array<{
  email: string
  plan: string
  issuedAt: number
}>

console.log('-- Generated by scripts/seed-legacy.ts — pre-seeded legacy licenses.')
console.log('-- Idempotent: re-running skips rows whose token hash already exists.')
console.log('begin;')
for (const record of records) {
  if (record.plan !== 'lifetime') {
    console.error(`skipping non-lifetime record: ${record.email} (${record.plan})`)
    continue
  }
  // Byte-for-byte the website's signLicense(): key order email, plan, issuedAt;
  // signature over the UTF-8 bytes of the base64url body string.
  const body = b64url(new TextEncoder().encode(
    JSON.stringify({ email: record.email, plan: record.plan, issuedAt: record.issuedAt }),
  ))
  const sig = await subtle.sign('Ed25519', privateKey, new TextEncoder().encode(body))
  const token = `${body}.${b64url(new Uint8Array(sig))}`
  const hash = await sha256Hex(token)

  const buyerEmail = record.email.trim().toLowerCase()
  const purchasedAt = new Date(record.issuedAt).toISOString()
  console.log(
    `insert into public.licenses (legacy_token_hash, buyer_email, plan, status, purchased_at)\n` +
      `  values (${sqlString(hash)}, ${sqlString(buyerEmail)}, 'lifetime', 'active', ${sqlString(purchasedAt)})\n` +
      `  on conflict (legacy_token_hash) do nothing;`,
  )
}
console.log('commit;')
