// Generates throwaway signing keys for the local test run and writes:
//   - supabase/functions/.env.test   → pass to `supabase functions serve --env-file`
//   - supabase/tests/.keys.test.json → read by the integration tests
//
// Both files are gitignored. Run from the repo root:
//   deno run -A scripts/setup-test-env.ts
// (Also invoked programmatically by the license-test MCP server.)

const subtle = globalThis.crypto.subtle

function toPem(der: ArrayBuffer, label: string): string {
  const b64 = btoa(String.fromCharCode(...new Uint8Array(der)))
  const lines = b64.match(/.{1,64}/g) ?? []
  return `-----BEGIN ${label}-----\n${lines.join('\n')}\n-----END ${label}-----\n`
}

async function generate() {
  const pair = (await subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify'])) as CryptoKeyPair
  const pkcs8 = await subtle.exportKey('pkcs8', pair.privateKey)
  const spki = await subtle.exportKey('spki', pair.publicKey)
  const publicJwk = (await subtle.exportKey('jwk', pair.publicKey)) as Record<string, unknown>
  delete publicJwk.key_ops
  delete publicJwk.ext
  return {
    privatePkcs8Pem: toPem(pkcs8, 'PRIVATE KEY'),
    privatePkcs8B64Der: btoa(String.fromCharCode(...new Uint8Array(pkcs8))),
    publicSpkiPem: toPem(spki, 'PUBLIC KEY'),
    publicJwk,
  }
}

export async function setupTestEnv(): Promise<{ envFile: string; keysFile: string }> {
  const entitlement = await generate()
  const legacy = await generate()

  const root = new URL('../', import.meta.url)

  const paddleWebhookSecret = 'pdl_ntfset_test_' + Array.from(
    crypto.getRandomValues(new Uint8Array(24)),
    (b) => b.toString(16).padStart(2, '0'),
  ).join('')

  // Polar shows the endpoint secret as a plain string and HMACs its UTF-8
  // bytes (see _shared/polar.ts) — so a throwaway random string is exactly
  // what the real thing looks like. Deliberately NOT base64/whsec_-prefixed:
  // the tests should exercise the same derivation production uses.
  const polarWebhookSecret = 'polar_whs_test_' + Array.from(
    crypto.getRandomValues(new Uint8Array(24)),
    (b) => b.toString(16).padStart(2, '0'),
  ).join('')

  // The admin-data endpoint refuses secrets under 32 chars, so the test
  // fixture has to be realistic rather than a short placeholder.
  const adminDataSecret = Array.from(
    crypto.getRandomValues(new Uint8Array(32)),
    (b) => b.toString(16).padStart(2, '0'),
  ).join('')

  const envFile = new URL('supabase/functions/.env.test', root)
  await Deno.writeTextFile(
    envFile,
    [
      '# Throwaway keys for local testing — generated by scripts/setup-test-env.ts',
      `ENTITLEMENT_PRIVATE_KEY=${btoa(entitlement.privatePkcs8Pem)}`,
      `LEGACY_SIGNING_KEY=${btoa(legacy.publicSpkiPem)}`,
      `PADDLE_WEBHOOK_SECRET=${paddleWebhookSecret}`,
      `POLAR_WEBHOOK_SECRET=${polarWebhookSecret}`,
      // Refund tests point the provider call at a local mock rather than
      // skipping the one path that moves money. host.docker.internal, NOT
      // 127.0.0.1: the function runs inside the edge-runtime container, where
      // loopback is the container's own — the mock listens on the host.
      'POLAR_API_KEY=polar_oat_test_dummy',
      'POLAR_API_BASE_URL=http://host.docker.internal:19998',
      `ADMIN_DATA_SECRET=${adminDataSecret}`,
      // No PADDLE_API_KEY on purpose: the email lookup must resolve from
      // stored customer.* events, and the no-email path must 500-and-release
      // so Paddle's retry can succeed later.
      // Dead endpoint on purpose: every claim-email send exercises the
      // best-effort failure path (§2.4) without touching the network.
      'RESEND_API_KEY=re_test_dummy',
      'RESEND_BASE_URL=http://127.0.0.1:19999',
      'SITE_URL=https://orchestra-automation.com',
      '',
    ].join('\n'),
  )

  const keysFile = new URL('supabase/tests/.keys.test.json', root)
  await Deno.writeTextFile(
    keysFile,
    JSON.stringify(
      {
        legacyPrivateKeyPkcs8B64: legacy.privatePkcs8B64Der,
        entitlementPublicJwk: entitlement.publicJwk,
        paddleWebhookSecret,
        polarWebhookSecret,
        adminDataSecret,
      },
      null,
      2,
    ),
  )

  return { envFile: envFile.pathname, keysFile: keysFile.pathname }
}

if (import.meta.main) {
  const { envFile, keysFile } = await setupTestEnv()
  console.log(`Wrote ${envFile}`)
  console.log(`Wrote ${keysFile}`)
  console.log('\nServe the functions with these keys:')
  console.log('  supabase functions serve --env-file supabase/functions/.env.test')
}
